package com.example.superheroes.models

import com.example.superheroes.R

data class Studios(
    val id : Int,
    val name: String,
    val description: String,
    val image : String,
    val publisherId : Int
){
    companion object {
        val studios = mutableListOf<Studios>(

// Marvel
            Studios(1, "Moon Knight",
                "Marc Spector era un mercenario hasta que fue traicionado y dejado por muerto en Egipto. Revivido por el dios Khonshu, Marc se convirtió en Moon Knight, el avatar del dios en la Tierra. Lucha contra el crimen usando sus habilidades de combate, fuerza aumentada por la luna y varias personalidades, lo que a menudo lo lleva al borde de la locura.",
                R.drawable.moonknight.toString(),
                1),
            Studios(2, "Squirrel girl",
                "Doreen Green es una heroína alegre con la habilidad de comunicarse con ardillas y poseer fuerza, agilidad y reflejos sobrehumanos. Aunque sus poderes parecen simples, ha derrotado a villanos poderosos como Doctor Doom y Thanos. Su optimismo y capacidad para resolver problemas la han convertido en un personaje sorprendentemente efectivo en el Universo Marvel.",
                R.drawable.squirrelgirl.toString(),
                1),
            Studios(3, "Blue Marvel",
                "Adam Brashear es un veterano de guerra y genio en física que, tras un accidente relacionado con antimateria, obtuvo habilidades sobrehumanas, como fuerza, vuelo y la capacidad de manipular energía antimateria. Como Blue Marvel, luchó contra el crimen en los años 60, pero se retiró después de que su identidad como superhéroe afroamericano fue revelada. Volvió a la acción años después para proteger al mundo.",
                R.drawable.bluemarvel.toString(),
                1),
            Studios(4, "Elsa Bloodstone",
                "Elsa Bloodstone es una cazadora de monstruos británica, hija del famoso cazador Ulysses Bloodstone. Posee fuerza sobrehumana, una resistencia increíble y es experta en el uso de armas mágicas. También tiene una piedra mística incrustada en su cuerpo que la hace inmortal y le proporciona habilidades adicionales para combatir criaturas sobrenaturales.",
                R.drawable.elsabloodstone.toString(),
                1),
            Studios(5, "Machine Man",
                "Aaron Stack es un androide avanzado creado por el Dr. Abel Stack. Machine Man posee fuerza sobrehumana, la capacidad de extender sus extremidades y conectarse con sistemas informáticos. Es un héroe que lucha por ser aceptado en la sociedad humana mientras combate amenazas tecnológicas y robóticas.",
                R.drawable.machineman.toString(),
                1),
            Studios(6, "Captain Britain",
                "Brian Braddock fue un joven físico que, tras un accidente, recibió poderes de Merlín y su hija Roma. Se convirtió en el campeón de Gran Bretaña como Captain Britain, con habilidades sobrehumanas de fuerza, vuelo y percepción extrasensorial. Es protector del multiverso y defensor de la justicia en su país.",
                R.drawable.captainbritain.toString(),
                1),
            Studios(7, "Mantis",
                "Mantis es una experta artista marcial con habilidades empáticas que le permiten influir en las emociones de los demás. También tiene la capacidad de comunicarse telepáticamente con seres cósmicos. Después de una vida de entrenamiento en un templo vietnamita, ha sido miembro de los Vengadores y los Guardianes de la Galaxia.",
                R.drawable.mantis.toString(),
                1),
            Studios(8, "Stingray",
                "Walter Newell es un oceanógrafo que desarrolló la identidad de Stingray tras diseñar una armadura para explorar y defender los océanos. Su traje le otorga la capacidad de volar y sobrevivir a grandes profundidades, además de proporcionarle resistencia física aumentada. Generalmente trabaja en colaboración con héroes acuáticos como Namor.",
                R.drawable.stingray.toString(),
                1),
            Studios(9, "Brother Voodoo",
                "Jericho Drumm es un practicante de magia vudú que, tras la muerte de su hermano, asumió el manto de Brother Voodoo. Es un poderoso hechicero capaz de controlar los espíritus y manipular la magia oscura. En un punto, incluso asumió el rol de Hechicero Supremo, encargado de proteger la realidad de amenazas mágicas.",
                R.drawable.jerichodrumm.toString(),
                1),
            Studios(10, "White Tiger",
                "Ava Ayala es la hermana menor del primer White Tiger. Después de heredar el amuleto de su hermano, obtuvo habilidades felinas como fuerza, agilidad y sentidos aumentados. Lucha para honrar el legado de su familia como defensora de los inocentes y miembro de los Vengadores Secretos.",
                R.drawable.whitetiger.toString(),
                1),

// DC
            Studios(11, "The Question",
                "Vic Sage es un periodista de investigación de Hub City que lucha contra la corrupción como el justiciero sin rostro conocido como The Question. Es un detective experto, maestro en artes marciales y filósofo que explora el sentido de la moralidad mientras se enfrenta a poderosos enemigos en una de las ciudades más corruptas del universo DC.",
                R.drawable.thequestion.toString(),
                2),
            Studios(12, "Aztek",
                "Aztek es el campeón de Quetzalcoatl, destinado a combatir la oscuridad. El guerrero elegido fue criado en secreto y entrenado para usar una armadura avanzada que le otorga vuelo, fuerza, invisibilidad y energía. Aunque su misión principal es combatir una amenaza profetizada, también ha colaborado con la Liga de la Justicia.",
                R.drawable.aztek.toString(),
                2),
            Studios(13, "Ragman",
                "Rory Regan es un vigilante de Gotham que usa un traje místico hecho de trapos, cada uno de los cuales contiene el alma de un criminal que ha capturado. El traje le otorga habilidades sobrehumanas, como fuerza y resistencia, y la capacidad de absorber las almas de criminales para aumentar su poder.",
                R.drawable.ragman.toString(),
                2),
            Studios(14, "Doctor Fate",
                "Kent Nelson es un arqueólogo que, tras descubrir el casco del dios Nabu, se convirtió en Doctor Fate, uno de los hechiceros más poderosos del universo DC. A través del casco, Nelson canaliza poderes mágicos casi ilimitados, que usa para defender la Tierra de amenazas sobrenaturales y cósmicas.",
                R.drawable.doctorfate.toString(),
                2),
            Studios(15, "Blue Beetle",
                "Jaime Reyes es un adolescente que encontró un escarabajo alienígena que se fusionó con su columna vertebral, proporcionándole una armadura tecnológica avanzada. Como Blue Beetle, tiene la capacidad de volar, disparar energía y formar armas a partir del traje. Su relación con el escarabajo a menudo lo pone en conflicto con entidades alienígenas.",
                R.drawable.bluebeetle.toString(),
                2),
            Studios(16, "Metamorpho",
                "Rex Mason fue expuesto a un meteorito raro que lo transformó en Metamorpho, el Hombre Elemento. Puede cambiar su cuerpo a cualquier forma o elemento químico, desde hierro hasta gas, lo que lo convierte en un héroe versátil en combate. A pesar de su trágica apariencia, sigue siendo un miembro confiable de equipos como la Liga de la Justicia.",
                R.drawable.metamorpho.toString(),
                2),
            Studios(17, "Elongated Man",
                "Ralph Dibny es un detective privado con la capacidad de estirar su cuerpo de maneras extremas, gracias a una poción derivada de la fruta gingo. Es conocido por su agudo sentido del humor y por ser uno de los mejores detectives del universo DC, ayudando a resolver casos complejos junto a héroes como Batman.",
                R.drawable.elongatedman.toString(),
                2),
            Studios(18, "The Phantom Stranger",
                "Un ser misterioso con orígenes enigmáticos, The Phantom Stranger actúa como intermediario entre el mundo humano y las fuerzas cósmicas y sobrenaturales. Posee vastos poderes mágicos y es conocido por intervenir en momentos cruciales, aunque rara vez revela sus verdaderas motivaciones.",
                R.drawable.thephantomstranger.toString(),
                2),
            Studios(19, "Animal Man",
                "Buddy Baker es un actor y padre de familia que, tras entrar en contacto con una energía alienígena, adquirió la capacidad de imitar las habilidades de cualquier animal. Puede volar como un ave, respirar bajo el agua como un pez o correr como un guepardo. A menudo equilibra su vida familiar con sus responsabilidades como superhéroe.",
                R.drawable.animalman.toString(),
                2),
            Studios(20, "Firestorm",
                "Firestorm es una fusión entre el joven Ronnie Raymond y el profesor Martin Stein, que, tras un accidente nuclear, se convirtieron en un solo ser con la capacidad de manipular la materia a nivel atómico. Ronnie controla el cuerpo, mientras que Stein actúa como una voz en su mente, proporcionando sabiduría y conocimiento científico.",
                R.drawable.firestorm.toString(),
                2),
        )
    }
}